# Generated by Django 5.0 on 2023-12-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastPasswordChange',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passwordResetToken',
            field=models.CharField(null=True),
        ),
    ]
