# Generated by Django 5.0 on 2023-12-29 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_alter_user_lastlogin_alter_user_lastpasswordchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='Password must be at least 8 characters long.')]),
        ),
    ]
