version: "3.8"
services:
  backend:
    build: ./backend/Gateway
    container_name: gp_gateway
    ports:
      - "4000:4000"
    volumes:
      - ./backend/Gateway:/app
  orthanc:
    build: ./backend/Services/orthanc
    container_name: gp_orthanc
    ports:
      - "8042:8042"
      - "4242:4242"
    stdin_open: true
    tty: true
    volumes:
      - ./backend/Services/Orthanc/config/orthanc.json:/etc/orthanc/orthanc.json
      - ./backend/Services/Orthanc/config/Scripts/initial_script.sh:/usr/share/orthanc/scripts/initial_script.sh
      - ./backend/Services/Orthanc/storage:/var/lib/orthanc/db-v6
  frontend:
    build: ./frontend
    container_name: gp_frontend
    ports:
      - "5000:5000"
    # stdin_open: true
    # tty: true
  

