version: "3.8"
services:
  backend:
    build: ./backend/Gatway
    container_name: gp_gateway
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - ./home/user/myapp/node_modules:/app/node_modules
  frontend:
    build: ./frontend
    container_name: gp_frontend
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
  
