version: "3.8"
services:

  frontend:
    build: ./frontend
    container_name: gp_frontend
    ports:
      - "5000:5000"
    depends_on:
      - api_gateway

  api_gateway:
    build: ./backend/ApiGateway
    container_name: gp_api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./backend/ApiGateway:/usr/src/app
    depends_on:
      - api_gateway_db
      - orthanc

  api_gateway_db:
    image: postgres:latest
    container_name: gp_gatway_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./backend/ApiGateway/pgdata:/var/lib/postgresql/data
    restart: always

  orthanc:
    build: ./backend/Services/Orthanc
    container_name: gp_orthanc
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - ./backend/Services/Orthanc/config/orthanc.json:/etc/orthanc/orthanc.json
      - ./backend/Services/Orthanc/config/dicomweb.json:/etc/orthanc/dicomweb.json
      - ./backend/Services/Orthanc/config/scripts:/usr/share/orthanc/scripts
      - ./backend/Services/Orthanc/storage:/var/lib/orthanc/db-v6

  rabbitmq:
    image: rabbitmq:3-management
    container_name: gp_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=mmm_ai
      - RABBITMQ_DEFAULT_PASS=mmm_mq_ai_p
    volumes:
      - ./backend/Services/RabbitMQ:/var/lib/rabbitmq

  nifti_storage:
    build: ./backend/Services/NiftiStorage/
    container_name: gp_nifti_storage
    ports:
      - "8080:8080"
    volumes:
      - ./backend/Services/NiftiStorage:/usr/src/app

  motion_artifacts_inference:
    build: ./backend/Services/Inference/Motion Artifacts
    container_name: gp_motion_artifacts_inference
    volumes:
      - ./backend/Services/Inference/Motion Artifacts:/usr/src/app
    depends_on:
      - rabbitmq

#  inference:
#    build: ./backend/Services/Inference
#    container_name: gp_inference
#    volumes:
#      - ./backend/Services/Inference:/usr/src/app
#    depends_on:
#      - rabbitmq

